{{- if .Values.mysql.backup.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ibmcase-mysql-restore
  namespace: {{ .Release.Namespace }}
  labels:
    app: bluecompute
    tier: data
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 0
  template:
    metadata:
      labels:
        app: bluecompute
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        tier: data
    spec:
      containers:
        - name: inventory-restore-container
          image: ibmcase/ibm-backup-restore
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          command: ["/scripts/docker-entrypoint.sh", "/bin/bash", "-c", "/backup_restore/vrestore"]
          env:
          - name: BACKUP_NAME
            value: {{ .Values.mysql.backup.backupName }}
          - name: BACKUP_DIRECTORY
            value: /var/lib/mysql
          - name: RESTORE_DIRECTORY
            value: /var/lib/mysql
          - name: SCHEDULE_TYPE
            value: {{ .Values.mysql.backup.scheduleType }}
          - name: SCHEDULE_INFO
            value: {{ .Values.mysql.backup.scheduleInfo }}Info
          - name: BACKUP_TYPE
            value: {{ .Values.mysql.backup.backupType }}Info
          - name: OBJECT_STORAGE_CREDENTIALS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mysql.backup.objStoreSecretName }}
                key: binding
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: {{ .Chart.Name }}-mysql
      volumes:
        - name: {{ .Chart.Name }}-mysql
          {{- if .Values.mysql.existingPVCName }}
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.existingPVCName }}
          {{ else }}
          hostPath:
            path: /var/lib/mysql
          {{ end }}
{{ end }}
