apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.internalPort }}
      targetPort: {{ .Values.mysql.service.externalPort }}
  selector:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
