apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ toYaml .Values.mysql.labels | indent 4 }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.internalPort }}
      targetPort: {{ .Values.mysql.service.externalPort }}
  selector:
{{ toYaml .Values.mysql.labels | indent 4 }}
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
